# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
#     runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        

    - uses: browser-actions/setup-chrome@latest
#     - name: Install Chrome
    - run: chrome --version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install selenium==4.4.3 webdriver-manager==3.8.3 chromedriver-autoinstaller==0.4.0
        #python -m pip install flake8 pytest
        if ( -f ./tests/requirements.txt ); then pip install -r requirements.txt; fi

    - name: Test of Authorization
      run: |
       #pytest ./tests/python_test.py
       python ./tests/python_test.py 
        
